version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maindb
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-files/:/var/lib/postgresql/data/
